from enum import Enum


class OperationCodeEnum(Enum):
    CREATE_EMPLOYEE = "CREATE_EMPLOYEE"
    AUTHORIZE_EMPLOYEE = "AUTHORIZE_EMPLOYEE"
    UNAUTHORIZE_EMPLOYEE = "UNAUTHORIZE_EMPLOYEE"

    ACTIVATE_PURCHASE = "ACTIVATE_PURCHASE"
    PAY_PURCHASE = "PAY_PURCHASE"
    CLAIM_PURCHASE = "CLAIM_PURCHASE"
    MANUAL_UNCLAIM_PURCHASE = "MANUAL_UNCLAIM_PURCHASE"
    AUTO_UNCLAIM_PURCHASE = "AUTO_UNCLAIM_PURCHASE"
    REFUND_PURCHASE = "REFUND_PURCHASE"
    CANCEL_PURCHASE = "CANCEL_PURCHASE"
    FINALIZE_CANCELLED_PURCHASE = "FINALIZE_CANCELLED_PURCHASE"

    ACTIVATE_SHIPMENT = "ACTIVATE_SHIPMENT"
    CANCEL_SHIPMENT = "CANCEL_SHIPMENT"
    RECEIVE_SHIPMENT = "RECEIVE_SHIPMENT"

    CREATE_PRODUCT = "CREATE_PRODUCT"
    UPDATE_PRODUCT = "UPDATE_PRODUCT"
    DELETE_PRODUCT = "DELETE_PRODUCT"

    MANUAL_TRIGGER_PURCHASE_FLOW = "MANUAL_TRIGGER_PURCHASE_FLOW"
    MANUAL_REDELIVER_TASKS = "MANUAL_REDELIVER_TASKS"
