graph TD
    domain.supplier_order --> domain.exceptions
    domain.supplier_order --> domain.stock_item
    domain.supplier_order --> domain.entity_id
    domain.supplier_order --> domain.entity_mixin
    domain.store_item --> domain.exceptions
    domain.store_item --> domain.entity_id
    domain.store_item --> domain.entity_mixin
    domain.cart --> domain.exceptions
    domain.cart --> domain.entity_mixin
    domain.cart --> domain.entity_id
    domain.customer_order --> domain.exceptions
    domain.customer_order --> domain.entity_mixin
    domain.customer_order --> domain.entity_id
    domain.customer_order --> domain.stock_item
    domain.customer --> domain.entity_mixin
    domain.customer --> domain.entity_id
    domain.inventory_service --> domain.store_item
    domain.inventory_service --> domain.entity_id
    domain.inventory_service --> domain.exceptions
    domain.inventory_service --> domain.stock_item
    domain.replenishment_service --> domain.exceptions
    domain.replenishment_service --> domain.inventory_service
    domain.replenishment_service --> domain.supplier_order
    domain.stock_item --> domain.entity_id
    domain.entity_mixin --> domain.entity_id
    domain.reservation_service --> domain.inventory_service
    domain.reservation_service --> domain.customer_order
    domain.reservation_service --> domain.exceptions
    domain.exceptions
    domain.entity_id