graph TD
    domain.supplier_order --> domain.exceptions
    domain.supplier_order --> domain.stock_item
    domain.supplier_order --> shared.entity_id
    domain.supplier_order --> shared.entity_mixin
    domain.store_item --> domain.exceptions
    domain.store_item --> shared.entity_id
    domain.store_item --> domain.stock_item
    domain.store_item --> shared.entity_mixin
    domain.cart --> domain.exceptions
    domain.cart --> shared.entity_id
    domain.cart --> shared.entity_mixin
    domain.customer_order --> domain.exceptions
    domain.customer_order --> domain.stock_item
    domain.customer_order --> shared.entity_mixin
    domain.customer_order --> shared.entity_id
    domain.customer --> shared.entity_mixin
    domain.customer --> shared.entity_id
    domain.stock_item --> shared.entity_id
    shared.entity_mixin --> shared.entity_id
    domain.services.reservation_service --> domain.exceptions
    domain.services.reservation_service --> domain.customer_order
    domain.services.reservation_service --> domain.store_item
    domain.services.replenishment_service --> domain.exceptions
    domain.services.replenishment_service --> domain.supplier_order
    domain.services.replenishment_service --> domain.store_item
    application.customer_order_service --> application.dtos
    application.customer_order_service --> application.interfaces
    domain.exceptions
    application.dtos
    application.customer_service
    shared.entity_id
    application.interfaces