from typing import Any, Literal, Protocol, Generic, Type, TypeVar

from infrastructure.query.load_query import LoadQuery

T = TypeVar("T")

class PRepository(Protocol, Generic[T]):
    model_type: Type[T]
    
    def create(self, items: list[T]) -> None: ...
    
    def read_by_attribute(self, attribute_name: str, values: list[Any]) -> list[T]: ...
    
    def update(self, items: list[T]) -> None: ...
    
    def delete(self, items: list[T]) -> None: ...
    def delete_by_attribute(self, attribute_name: str, values: list[Any]) -> None: ...
    
    def fill(self, items: list[T]) -> None: ...
    
    def load_from_query(self, query: LoadQuery) -> list[T]: ...
    
    def save(self, difference: dict[Literal['CREATED', 'UPDATED', 'DELETED'], list[dict[str, Any]]]) -> None: ...