"""initial migration

Revision ID: 5d979f595823
Revises:
Create Date: 2025-12-29 20:45:03.428646

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from shop_project.infrastructure.persistence.database.seq_type import SeqType
from shop_project.infrastructure.persistence.database.utc_datetime import UTCDateTime

# revision identifiers, used by Alembic.
revision: str = "5d979f595823"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("subject_type", sa.String(length=50), nullable=False),
        sa.Column("password_verifier", sa.String(length=255), nullable=True),
        sa.Column("login", sa.String(length=50), nullable=True),
        sa.Column("phone_number", sa.String(length=50), nullable=True),
        sa.Column("email", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "external_id_totp",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("external_id_type", sa.String(length=50), nullable=False),
        sa.Column("external_id", sa.String(length=50), nullable=False),
        sa.Column("totp_verifier", sa.String(length=255), nullable=False),
        sa.Column("issued_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("expiration", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "operation_log",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("seq", SeqType(), autoincrement=True, nullable=False),
        sa.Column("operation_code", sa.String(length=50), nullable=False),
        sa.Column("payload_json", sa.String(length=255), nullable=False),
        sa.Column("occured_at", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("seq"),
        sa.UniqueConstraint("entity_id"),
        sa.UniqueConstraint("seq"),
    )
    op.create_table(
        "product",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "shipment",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "shipment_summary",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "task",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("handler", sa.String(length=50), nullable=False),
        sa.Column("params_json", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "auth_session",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("issued_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("expiration", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "customer",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "employee",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "manager",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "shipment_item",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["shipment.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.entity_id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "product_id"),
    )
    op.create_table(
        "shipment_summary_item",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["shipment_summary.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.entity_id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "product_id"),
    )
    op.create_table(
        "claim_token",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("token_fingerprint", sa.String(length=255), nullable=False),
        sa.Column("issued_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("expiration", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["customer.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "escrow_account",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("total_amount", sa.Numeric(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "purchase_draft",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "purchase_active",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("escrow_account_id", sa.Uuid(), nullable=False),
        sa.Column("state", sa.String(length=50), nullable=False),
        sa.Column("reserved_until", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["escrow_account_id"],
            ["escrow_account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "purchase_draft_item",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["purchase_draft.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.entity_id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "product_id"),
    )
    op.create_table(
        "purchase_summary",
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("escrow_account_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customer.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["escrow_account_id"],
            ["escrow_account.entity_id"],
        ),
        sa.PrimaryKeyConstraint("entity_id"),
    )
    op.create_table(
        "purchase_active_item",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["purchase_active.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.entity_id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "product_id"),
    )
    op.create_table(
        "purchase_summary_item",
        sa.Column("parent_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["purchase_summary.entity_id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.entity_id"],
        ),
        sa.PrimaryKeyConstraint("parent_id", "product_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchase_summary_item")
    op.drop_table("purchase_active_item")
    op.drop_table("purchase_summary")
    op.drop_table("purchase_draft_item")
    op.drop_table("purchase_active")
    op.drop_table("purchase_draft")
    op.drop_table("escrow_account")
    op.drop_table("claim_token")
    op.drop_table("shipment_summary_item")
    op.drop_table("shipment_item")
    op.drop_table("manager")
    op.drop_table("employee")
    op.drop_table("customer")
    op.drop_table("auth_session")
    op.drop_table("task")
    op.drop_table("shipment_summary")
    op.drop_table("shipment")
    op.drop_table("product")
    op.drop_table("operation_log")
    op.drop_table("external_id_totp")
    op.drop_table("account")
    # ### end Alembic commands ###
