"""operation_log.payload_json type TEXT

Revision ID: 9d8407e07fa0
Revises: 5d979f595823
Create Date: 2026-01-03 18:18:35.070086

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9d8407e07fa0"
down_revision: Union[str, Sequence[str], None] = "5d979f595823"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operation_log",
        "payload_json",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Text(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operation_log",
        "payload_json",
        existing_type=sa.Text(),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
