from typing import Any, Protocol


class PSession(Protocol):
    def begin(self) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def add(self, obj: Any) -> None: ...
    def delete(self, obj: Any) -> None: ...
    def close(self) -> None: ...