CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}`;

CREATE USER IF NOT EXISTS '${CDC_USER}'@'%' IDENTIFIED BY '${CDC_PASSWORD}';

GRANT SELECT, RELOAD, SHOW DATABASES,
      REPLICATION SLAVE, REPLICATION CLIENT
ON *.* TO '${CDC_USER}'@'%';

CREATE DATABASE IF NOT EXISTS maxwell;

GRANT ALL PRIVILEGES ON maxwell.* TO '${CDC_USER}'@'%';

FLUSH PRIVILEGES;