from typing import Any, Protocol, Self, Type
from uuid import UUID

from shop_project.application.interfaces.interface_query_plan import IQueryPlan
from shop_project.domain.interfaces.persistable_entity import PersistableEntity


class IQueryBuilder(Protocol):
    def __init__(self, mutating: bool) -> None: ...

    def _build_query(self) -> None: ...

    # TODO interface for prebuilt queries
    # def add_prebuilt(self, prebuilt_query: CustomQuery) -> Self:
    #     ...

    def load(self, entity_type: Type[PersistableEntity]) -> Self: ...

    def and_(self) -> Self: ...

    def or_(self) -> Self: ...

    def greater_than(self, attribute_name: str, value: Any) -> Self: ...

    def lesser_than(self, attribute_name: str, value: Any) -> Self: ...

    def from_attribute(
        self, attribute_name: str, attribute_values: list[Any]
    ) -> Self: ...

    def from_id(self, attribute_values: list[UUID]) -> Self: ...

    def for_update(self, no_wait: bool = False) -> Self: ...

    def for_share(self, no_wait: bool = False) -> Self: ...

    def no_lock(self) -> Self: ...

    def from_previous(self, query_index: int | None = None) -> Self: ...

    def build(self) -> IQueryPlan: ...
