from typing import Literal, Protocol, Generic, Type, TypeVar

from shop_project.domain.p_aggregate import PAggregate
from shop_project.infrastructure.query.load_query import LoadQuery
from shop_project.shared.entity_id import EntityId

T = TypeVar("T", bound=PAggregate)

class PRepository(Protocol, Generic[T]):
    model_type: Type[T]
    
    def create(self, items: list[T]) -> None: ...
    
    def read_by_attribute(self, attribute_name: str, values: list[str]) -> list[T]: ...
    def read_all(self) -> list[T]: ...
    
    def update(self, items: list[T]) -> None: ...
    
    def delete(self, items: list[T]) -> None: ...
    def delete_by_attribute(self, attribute_name: str, values: list[str]) -> None: ...
    
    def fill(self, items: list[T]) -> None: ...
    
    def load_from_query(self, query: LoadQuery) -> list[T]: ...
    
    def save(self, difference_snapshot: dict[Literal['CREATED', 'UPDATED', 'DELETED'], list[dict[str, str]]]) -> None: ...
    
    def get_unique_id(self) -> EntityId: ...